# Generated by Django 2.0.6 on 2019-03-01 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dateofEntry', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
